// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"github.com/google/uuid"
)

type Thing struct {
	ID   int32     `json:"id"`
	Code uuid.UUID `json:"code"`
	Name string    `json:"name"`
}
