// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Error defines model for error.
type Error struct {
	Message string `json:"message"`
}

// Thing defines model for thing.
type Thing struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// Code defines model for code.
type Code string

// PageNumber defines model for pageNumber.
type PageNumber int32

// PageSize defines model for pageSize.
type PageSize int32

// N400 defines model for 400.
type N400 Error

// FindThingParams defines parameters for FindThing.
type FindThingParams struct {

	// page number
	PageNumber *PageNumber `json:"pageNumber,omitempty"`

	// page size
	PageSize *PageSize `json:"pageSize,omitempty"`
}

// CreateThingJSONBody defines parameters for CreateThing.
type CreateThingJSONBody Thing

// UpdateThingJSONBody defines parameters for UpdateThing.
type UpdateThingJSONBody Thing

// CreateThingJSONRequestBody defines body for CreateThing for application/json ContentType.
type CreateThingJSONRequestBody CreateThingJSONBody

// UpdateThingJSONRequestBody defines body for UpdateThing for application/json ContentType.
type UpdateThingJSONRequestBody UpdateThingJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /things)
	FindThing(ctx echo.Context, params FindThingParams) error

	// (POST /things)
	CreateThing(ctx echo.Context) error

	// (PUT /things)
	UpdateThing(ctx echo.Context) error

	// (DELETE /things/{code})
	DeleteThing(ctx echo.Context, code Code) error

	// (GET /things/{code})
	GetThingsCode(ctx echo.Context, code Code) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// FindThing converts echo context to params.
func (w *ServerInterfaceWrapper) FindThing(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FindThingParams
	// ------------- Optional query parameter "pageNumber" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageNumber", ctx.QueryParams(), &params.PageNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageNumber: %s", err))
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageSize: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindThing(ctx, params)
	return err
}

// CreateThing converts echo context to params.
func (w *ServerInterfaceWrapper) CreateThing(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateThing(ctx)
	return err
}

// UpdateThing converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateThing(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateThing(ctx)
	return err
}

// DeleteThing converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteThing(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "code" -------------
	var code Code

	err = runtime.BindStyledParameterWithLocation("simple", false, "code", runtime.ParamLocationPath, ctx.Param("code"), &code)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteThing(ctx, code)
	return err
}

// GetThingsCode converts echo context to params.
func (w *ServerInterfaceWrapper) GetThingsCode(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "code" -------------
	var code Code

	err = runtime.BindStyledParameterWithLocation("simple", false, "code", runtime.ParamLocationPath, ctx.Param("code"), &code)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetThingsCode(ctx, code)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/things", wrapper.FindThing)
	router.POST(baseURL+"/things", wrapper.CreateThing)
	router.PUT(baseURL+"/things", wrapper.UpdateThing)
	router.DELETE(baseURL+"/things/:code", wrapper.DeleteThing)
	router.GET(baseURL+"/things/:code", wrapper.GetThingsCode)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xWTXPbOAz9KxzsHjWWHacX3fox3eml09mkp24OjAjJ7EgkS4JunIz++w5JyZYjxdrd",
	"yWGnJ1sCCD48PAB6glK3RitU5KB4AsMtb5HQxqdSCwy/Al1ppSGpFRSAiiQdWDRmIMMrw2kHGSjeIhTQ",
	"Wyz+8NKigIKsxwxcucOWh3j4wFvTIBSbq20GlbYtJyjAeykgAzqYEMWRlaqGrsvA8Bo/+/Ye7RRNsDGV",
	"jD2aHx7t4QRndHoMQmDFfUNQbLIToDEcqWh7BRm0UsnWt9GxxyYVYY32CO5GPuIL0FwwvQzsJplnYF29",
	"GeF6s54Dxh96YOv1AswulMMZrRzGyl6v16nAilBR+MuNaWTJA/T8uwv4n0aofrdYQQG/5Se55MnqcrRW",
	"93ec5/+OCxZEgI6gy+B6vZly9FVxTztt5SMKxssSnUu+26nv22hmShPjTaN/okiu11PXz5rYR+2ViCXq",
	"kUbpRbBB6VYbtCQTHy06x2s8Eyfc7qRj0jHaIYvn2OA2J9KT3L8dw90dHfX9dywjDbQLJyYIhl4b9cZi",
	"awxKGoN2usV0xRLIvk1jiCnQ4C1VpQeZ8DLKpJculQ222kEG3jZQwI7IuCLPa0k7f78qdZsPLhNZ3AZ0",
	"jr398onhg9EOHQtEROk5ZrHBPVfEqsA3V7yWqmacxZyYI215jX+pkJ2koUx9PMhgj9alazarzXq1Dtdr",
	"g4obCQVsV+FVFudVZD2PYePfGmmqoz+RvFUu6K1HEDhhldVtlEWPB+IlKYVPAgr4KJW47aswnqnf5lvp",
	"5JKPplWX/SPvOEK6u2cdfvUvO1wStm6p1ZOwuqNYuLX8MNf6Nz72auUbZnzTMF2N6EsHjHYzhL+3yAnd",
	"UPAJsck+UNtPl3daHF5tnPU5nndL2GDdhOGZeXZKvDmwMoIVjDOFP9kosPEzqX81IqY+Iup59snlf5L9",
	"eiF7H8FOsu+yoevypzCCuhSmQZpZoel9kIOTqm6wJ+eeOxRMq9iDIQgzVu+lQDGh7EOM8N96MU7Ilzrr",
	"QuYJtWDOYCkrWZ5pPxuW79zlx4vy4HRamku+m9HSXPLdjrbmku91ksLl2ajmEg3LXFshVVMfGOlYqaFI",
	"sWRxhp/X6g+kNMzfp9X0itV67ea4UP1h4P0i1Y8fUGj3QxXOM/9itfBleGCo9tJq1Qaan38XGKvFKvIQ",
	"vw24kXlcb89opLTtL0VyxGtcDvUB99hoE0JcDCdwPwl21/0dAAD//40sevQXDQAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}

